---
title: Base
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sets:
    title: Sets
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: sets
  values:
    _hide_content: true
- scope:
    path: index.html
  values:
    body_class: show_hero_search
url: https://orange-ape.cloudvent.net/
baseurl: 
google_analytics_key: 
disqus_shortname: 
logo: "/siteicon.png"
description: Knowledge base template for Jekyll.
author:
  name: 
  email: 
  twitter: 
social:
  name: Base Template
  links:
  - https://github.com/CloudCannon/base-jekyll-template
permalink: "/:categories/:title/"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Google Plus
- Instagram
- LinkedIn
- Pinterest
- Tumblr
- Twitter
- YouTube
- Email
- RSS
types:
- Document
- Video
_comments: 
